# Generated by Django 4.1.7 on 2023-04-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='racing',
            new_name='rating',
        ),
    ]
